name: Go Matrix
on: [push, pull_request]

jobs:
  cross:
    name: Go
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 0

    strategy:
      matrix:
        go-version: [ 1.19, 1.x ]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Set up Go environment
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.go-version }}-go-

      # Test Go code
      - name: Test
        run: go test -v -cover ./...
